CMake Error at /home/sycamore/ros2_galactic/ros2-linux/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
  interfaces --arguments-file
  /home/sycamore/Syca_ws/build/interfaces/rosidl_adapter__arguments__interfaces.json
  --output-dir
  /home/sycamore/Syca_ws/build/interfaces/rosidl_adapter/interfaces
  --output-file
  /home/sycamore/Syca_ws/build/interfaces/rosidl_adapter/interfaces.idls)
  returned error code 1:

  Traceback (most recent call last):

    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/home/sycamore/ros2_galactic/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/home/sycamore/ros2_galactic/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/home/sycamore/ros2_galactic/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 24, in convert_to_idl
      return convert_srv_to_idl(
    File "/home/sycamore/ros2_galactic/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/srv/__init__.py", line 28, in convert_srv_to_idl
      srv = parse_service_string(package_name, input_file.stem, content)
    File "/home/sycamore/ros2_galactic/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 852, in parse_service_string
      request_message = parse_message_string(
    File "/home/sycamore/ros2_galactic/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 540, in parse_message_string
      msg = MessageSpecification(pkg_name, msg_name, fields, constants)
    File "/home/sycamore/ros2_galactic/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 387, in __init__
      self.base_type = BaseType(
    File "/home/sycamore/ros2_galactic/ros2-linux/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 204, in __init__
      raise InvalidResourceName(

  rosidl_adapter.parser.InvalidResourceName: 'task_Request' is an invalid
  message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'

Call Stack (most recent call first):
  /home/sycamore/ros2_galactic/ros2-linux/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:19 (rosidl_generate_interfaces)


